swagger: '2.0'
info:
  title: testcase-generation-event-dispatcher-api
  description: api
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header

# Apply security globally to all endpoints
security:
  - api_key: []

paths:
  /dispatch:
    post:
      summary: Dispatch a job
      description: Publishes events to a pubsub topic for each issue ID provided in the request body.
      operationId: dispatch
      x-google-backend:
        address: ${backend_url}
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/DispatchRequest'
      responses:
        '200':
          description: A successful response
          schema:
            type: object
            properties:
              errors:
                type: boolean
              unprocessedIssues:
                type: array
                items:
                  type: array
                  items:
                    type: string
        '400':
          description: Invalid request
          schema:
            type: object
            properties:
              success:
                type: boolean
              error:
                type: string
        '500':
          description: Internal server error
          schema:
            type: object
            properties:
              success:
                type: boolean
              error:
                type: string

definitions:
  DispatchRequest:
    type: object
    required:
      - issueIds
    properties:
      issueIds:
        type: array
        items:
          type: string
