INSERT INTO custom_rule_tag (id, name, description, created_at, updated_at) VALUES
(lower(hex(randomblob(16))), 'access-control', 'Permission enforcement', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'access-review', 'Permission review cycles', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'accountability', 'User action traceability', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'admin-controls', 'Administrative safeguards', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'alarm-management', 'Safety alert behavior', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'anomaly-detection', 'Detect unusual behavior', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'architecture', 'System architecture definition', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'asset-management', 'Track systems and devices', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'audit', 'Internal auditability', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'audit-logs', 'Regulatory activity logging', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'authentication', 'Identity verification', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'authorization', 'Role permission checking', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'breach-notification', 'Breach reporting obligations', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'business-continuity', 'Continuity planning', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'change-management', 'Controlled system changes', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'checksum', 'Corruption detection', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'ci-cd-security', 'Secure CI/CD pipelines', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'clinical-data', 'Patient health data', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'clinical-safety', 'Patient safety assurance', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'clinical-testing', 'Clinical performance testing', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'clinical-validation', 'Validate clinical workflows', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'clinical-workflows', 'Validate clinical processes', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'compatibility', 'Module interoperability', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'competence', 'Staff competency assurance', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'complaints', 'Complaint handling process', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'compliance-testing', 'Regulatory compliance testing', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'config-management', 'Controlled configuration', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'containment', 'Limit incident impact', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'corrective-action', 'Fix root issues', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'data-disposal', 'Secure irreversible deletion', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'data-encryption', 'Encrypt sensitive information', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'data-integrity', 'Prevent unauthorized changes', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'data-retention', 'Controlled data storage duration', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'defects', 'Product defect detection', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'dependency-security', 'Safe third-party components', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'design', 'Design process control', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'design-review', 'Formal design assessment', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'device-interoperability', 'Safe device integration', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'disaster-recovery', 'Recovery after failures', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'documentation', 'Controlled document management', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'ephi-handling', 'Electronic PHI protection', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'esignature', 'Electronic signature', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'failure-mode', 'Detect failure points', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'feedback', 'Customer feedback handling', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'forensics', 'Post-incident investigation', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'gdpr', 'GDPR compliance requirements', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'hardening', 'Reduce attack surface', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'hazard-analysis', 'Identify potential hazards', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'hazard-protection', 'Prevent hazardous outcomes', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'hipaa', 'HIPAA compliance requirements', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'identity-proofing', 'Verify real identity', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'immutable-logs', 'Tamper-proof audit logs', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'incident-response', 'Security incident handling', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'input-validation', 'Validate user inputs', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'integration-testing', 'Module interaction testing', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'interfaces', 'Interface behavior management', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'interoperability', 'System compatibility', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'logging', 'System event capture', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'masking', 'Hide sensitive fields', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'medical-calculations', 'Validate medical formulas', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'medical-workflow', 'Clinical process validation', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'media-control', 'Secure device/media handling', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'metrics', 'Performance measurement', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'mfa', 'Multi-factor authentication', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'model-governance', 'AI model oversight', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'monitoring', 'Continuous system oversight', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'nonconformity', 'Identify unmet requirements', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'operations', 'Operational procedures', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'output-encoding', 'Prevent unsafe outputs', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'patient-impact', 'Patient outcome relevance', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'performance-testing', 'Load and latency testing', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'phi-handling', 'Health data protection', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'physical-security', 'Facility & device protection', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'pii-handling', 'Personal data protection', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'planning', 'Structured project planning', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'privilege-escalation', 'Unauthorized privilege gain', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'rbac', 'Role-based access control', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'rca', 'Root cause analysis', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'records', 'Electronic records', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'record-keeping', 'Maintain compliance records', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'regression', 'Post-change verification', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'regression-testing', 'Post-change verification', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'release', 'Controlled release management', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'requirements', 'Controlled requirement handling', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'retrieval', 'Data access retrieval', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'risk-assessment', 'Identify system risks', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'risk-class', 'SaMD safety classification', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'risk-control', 'Risk mitigation verification', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'risk-management', 'Manage organizational risks', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'risk-mitigation', 'Apply risk controls', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'safety', 'Ensure safe outcomes', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'secure-coding', 'Safe development practices', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'security-rule', 'HIPAA security safeguards', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'session-security', 'Session protection', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'soup', 'Third-party component handling', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'soup-validation', 'SOUP component verification', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'source-control', 'Code version management', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'system-testing', 'End-to-end system checks', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'tls-security', 'Encrypted data transport', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'traceability', 'Requirement-to-output linkage', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'training', 'Workforce skill development', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'unit-testing', 'Component-level testing', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'usability', 'User experience validation', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'usability-testing', 'User workflow testing', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'validation', 'Validate output meets needs', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'vendor-management', 'Manage external suppliers', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'verification', 'Requirements confirmation', datetime('now'), datetime('now')),
(lower(hex(randomblob(16))), 'workflow', 'Clinical process flow', datetime('now'), datetime('now'));
